language: php
php:
  - '7.0'
  - '7.1'
notifications:
  email: false
cache:
  directories:
    - node_modules
before_install:
  - composer clear-cache
install:
  - composer install --no-interaction --no-ansi --no-progress --no-suggest
  - composer global require phpunit/phpunit
script:
  - phpunit
