language: php
php:
  - '7.0'
  - '7.1'
before_script:
  - composer self-update
  - composer install --no-interaction
  - composer global require phpunit/phpunit
script:
  - phpunit
notifications:
  email: false
