language: php
php:
  - '7.0'
  - '7.1'
notifications:
  email: false
cache:
  directories:
    - node_modules
before_install:
  - nvm install node
  - nvm use node
  - npm prune
  - composer clear-cache
install:
  - npm install
  - composer install --no-interaction --no-ansi --no-progress --no-suggest
  - composer global require phpunit/phpunit
script:
  - phpunit
after_success:
  - npm run semantic-release
